### ISSUE TITLE
List of upcoming events

### ISSUE THREAD

**Issue by MarshallJD1** [MarshallJD1/project-planning-demo#1]
**User story**

as a local resident I want to see a list of upcoming community events 

**acceptance criteria** 

- [ ] the homepage displays a list of upcoming community events
- [ ]  each event listing includes the event name , day , time and a brief description,
- [ ] the list is responsive and looks good on all main device sizes 

**tasks** 

- [ ] add a html section on the homepage dedicated to the upcoming community events.
- [ ] style the event list using bootstrap
- [ ] add some upcoming events including event time , date name and brief description.
